### ISSUE TITLE
First error!

### ISSUE THREAD

**Issue by TechnoCube** [jakofranko/tilt-server#1]
I'm gonna keep playing with this but I got this error while trying to get some activity in the console and I'm not sure if it was a regular data point or a "comment" that I pushed from the tilt android app that caused the exception. I also thought it would be fun to try out this github Issues feature. Enjoy the following console output:

Tilt Server listening at http://localhost:3000
Headers: {
  host: '192.168.1.36:3000',
  connection: 'keep-alive',
  'content-length': '96',
  accept: '*/*',
  'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Lenovo TAB 2 A10-70F Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.50 Safari/537.36',
  'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
  'x-requested-with': 'com.baronbrew.tiltcordova',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'en-US,en;q=0.9'
}
Body: {}
TypeError: Cannot destructure property 'Beer' of 'tiltEvent.parameter' as it is undefined.
    at sanitizeTiltEvent (C:\Users\TechnoCube\tilt_projects\node_server\dist\utils.js:9:19)
    at C:\Users\TechnoCube\tilt_projects\node_server\dist\controllers\tilt-data.js:36:60
    at Layer.handle [as handle_request] (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\index.js:174:3)
Headers: {
  'accept-charset': 'UTF-8',
  'content-type': 'application/x-www-form-urlencoded; charset=utf-8',
  'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 11; ONEPLUS A6003 Build/RKQ1.201217.002)',
  host: '192.168.1.36:3000',
  connection: 'Keep-Alive',
  'accept-encoding': 'gzip',
  'content-length': '89'
}
Body: {}
TypeError: Cannot destructure property 'Beer' of 'tiltEvent.parameter' as it is undefined.
    at sanitizeTiltEvent (C:\Users\TechnoCube\tilt_projects\node_server\dist\utils.js:9:19)
    at C:\Users\TechnoCube\tilt_projects\node_server\dist\controllers\tilt-data.js:36:60
    at Layer.handle [as handle_request] (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\TechnoCube\tilt_projects\node_server\node_modules\express\lib\router\index.js:174:3)

**Comment by jakofranko** [comment]
we got this all taken care of! I was using the wrong body parser.
